### ISSUE TITLE
[BUG] QFI header not added to gtp packet

### ISSUE THREAD

**Issue by zhemant** [HewlettPackard/PacketRusher#134] opened 2024-07-24 15:07 UTC
**Describe the bug**
Core is sending qfi 1 to PacketRusher, we can see in the logs it receives and acknowledges. However when we send traffic from UE, the GTP packet sent out does not have QFI in the GTP header. This causes the packet to be dropped on UPF.

**To Reproduce**

Compile using current main branch, attach 1 UE to 5G Core, when 5G Core sends QFI, it will be visible in logs, now try to ping and capture the traffic, the QFI header will be missing from GTP packet.

**Expected behavior**
QFI header should be added in GTP packet if sent from the core

**Screenshots**

**Architecture (please complete the following information):**
- OS:  Ubuntu 22.04
- Platform: x86-64
- Version: 22
- Kernel : 5.15.0-116-generic

**Log:**
```sh
INFO[0001] [GNB][NGAP] Receive PDU Session Resource Setup Request 
INFO[0001] [GNB][NGAP][UE] PDU Session was created with successful. 
INFO[0001] [GNB][NGAP][UE] PDU Session Id: 1            
INFO[0001] [GNB][NGAP][UE] NSSAI Selected --- sst: NSSAI was not selected sd: NSSAI was not selected 
INFO[0001] [GNB][NGAP][UE] PDU Session Type: ipv4       
INFO[0001] [GNB][NGAP][UE] QOS Flow Identifier: 1       
INFO[0001] [GNB][NGAP][UE] Uplink Teid: 5               
INFO[0001] [GNB][NGAP][UE] Downlink Teid: 1             
INFO[0001] [GNB][NGAP][UE] Non-Dynamic-5QI: 9           
INFO[0001] [GNB][NGAP][UE] Priority Level ARP: 2        
INFO[0001] [GNB][NGAP][UE] UPF Address: 192.168.130.10 :2152 
INFO[0001] [GNB] Initiating PDU Session Resource Setup Response 
INFO[0001] [UE][NAS] Message with security header       
INFO[0001] [UE][NAS] Message with integrity and ciphered 
INFO[0001] [UE][NAS] successful NAS CIPHERING           
INFO[0001] [UE][NAS] successful NAS MAC verification    
INFO[0001] [UE][NAS] Receive DL NAS Transport           
INFO[0001] [UE][NAS] Receiving PDU Session Establishment Accept 
INFO[0001] [UE][NAS] PDU session QoS RULES: [1 0 6 49 49 1 1 255 1] 
INFO[0001] [UE][NAS] PDU session DNN: default.mnc001.mcc001.gprs 
INFO[0001] [UE][NAS] PDU session NSSAI -- sst: 1 sd: 000 
INFO[0001] [UE][NAS] PDU address received: 192.168.6.1  
DEBU[0002] [UE][GTP] Setting up GTP Forwarding Action Rule for val0000012345 1 --action 2 
DEBU[0002] [UE][GTP] Setting up GTP Forwarding Action Rule for val0000012345 2 --action 2 --hdr-creation 0 5 192.168.130.10 2152 
DEBU[0002] [UE][GTP] Setting up GTP Packet Detection Rule for val0000012345 1 --pcd 1 --hdr-rm 0 --ue-ipv4 192.168.6.1 --f-teid 1 192.168.130.20 --far-id 1 
DEBU[0002] [UE][GTP] Setting Up GTP Packet Detection Rule for val0000012345 2 --pcd 2 --ue-ipv4 192.168.6.1 --far-id 2 
INFO[0002] [UE][GTP] Interface val0000012345 has successfully been configured for UE 192.168.6.1 
INFO[0002] [UE][GTP] You can do traffic for this UE using VRF vrf0000012345, eg: 
INFO[0002] [UE][GTP] sudo ip vrf exec vrf0000012345 iperf3 -c IPERF_SERVER -p PORT -t 9000 
```

How is current seen in wireshark:
![image](https://github.com/user-attachments/assets/9226cc0f-7ea5-487f-9024-157cd3396fcf)

Expected in wireshark:
![image](https://github.com/user-attachments/assets/3e4b8933-3dd1-41e9-92bb-ee7805363f22)

**Comment by linouxis9** [comment] 2024-07-24 16:12
Hi @zhemant,

Thanks a lot for opening this issue. PacketRusher does not yet support adding QFI.
The issue is that when setting QFI in gtp5g to enable the creation of the Extension Header, gtp5g will by default create a DL PDU SESSION INFORMATION Container:
https://github.com/free5gc/gtp5g/blob/162be58c7879287d8750019a7b1633785a2c6e4c/src/gtpu/pktinfo.c#L298-L306

This can't be configured, and tweaking it in our embedded gtp5g would mean we would become incompatible running with a Free5GC's UPF on the same host (notably in k8s usecases).

The proper solution would be to implement the tweaking of this parameter upstream in Free5GC's gtp5g but I haven't had the time to do that. It's maybe time I do that :-) (cc: @ianchen0119 FYI)

In the meanwhile, you may make things work by tweaking PacketRusher as-is:

In internal/control_test_engine/ue/gtp/service/service.go after this line (https://github.com/HewlettPackard/PacketRusher/blob/32a08fa9fb2d83b654628b5187a0244a66b737b2/internal/control_test_engine/ue/gtp/service/service.go#L101 add the following code:
```go
	qfi := pduSession.GnbPduSession.GetQosId()
	cmdAddQer := []string{nameInf, "1", "--qfi", strconv.Itoa(int(qfi))}
	if qfi > 0 {
		log.Debug("[UE][GTP] Setting Up QFI", strings.Join(cmdAddQer, " "))
	        if err := gtpTunnel.CmdAddQER(cmdAddQer); err != nil {
		     log.Fatal("[UE][GTP] Unable to create QER:", err)
		     return
	        }
		cmdAddPdr = append(cmdAddPdr, "--qer-id", strconv.Itoa(int(qfi)))
	}
```

And replace this line
https://github.com/HewlettPackard/PacketRusher/blob/32a08fa9fb2d83b654628b5187a0244a66b737b2/lib/gtp5g/src/gtpu/pktinfo.c#L299
with:
```go
dl_pdu_sess->pdu_sess_ctr.type_spare = PDU_SESSION_INFO_TYPE1;
```

Then recompile gtp5g (and reinstall the new module), then PacketRusher as in the instructions.

Thanks a ton,
Valentin

**Comment by linouxis9** [comment] 2024-07-27 13:34
Hi @zhemant,

Thanks a ton for opening this issue. Your issue should be fixed by this PR: https://github.com/HewlettPackard/PacketRusher/pull/135
Please read the instructions in the PR's description and ensure that this PR fixes your issue.

Thanks a ton!
Valentin

**Closed** 2024-11-28 07:36 UTC
Labels: bug
