### ISSUE TITLE
Incorrect 5GS Mobile identity in InitialUEMessage Registration request

### ISSUE THREAD

**Issue by hug0lin** [HewlettPackard/PacketRusher#126] opened 2024-05-22 21:43 UTC
Packetrusher sends in NGAP/NAS-5GS InitialUEMessages Registration request  field "5GS Mobile Identity" with length=0. For 5GC, which make a correct field check (length should be 6 to n) this means refusal of registration.

<img width="1254" alt="image" src="https://github.com/HewlettPackard/PacketRusher/assets/130478827/2cd359fd-ce54-438b-b97a-fcea7df2742d">

As specified in TS 24.501 (Table 8.2.6.1.1) this field is mandatory for Registration Request with defined structure  
<img width="698" alt="image" src="https://github.com/HewlettPackard/PacketRusher/assets/130478827/82476fd4-7cf3-447c-8f7f-81f898497628">

I understand that the implementation of 5GS Mobile Identity is very complicated (see 9.11.3.4 5GS mobile identity options - SUCI, the 5G-GUTI, the IMEI, the IMEISV, the 5G-S-TMSI, the MAC address or the EUI-64.), but it would be useful to implement at least basic registration and de-registration using SUCI.

**Comment by linouxis9** [comment] 2024-05-22 21:51
Hi @hug0lin!
Thanks for opening this issue. This is weird as PacketRusher definitely supports Registration using SUCI (raw SUPI encoded as SUCI without any Profile A or Profile B encryption though) or with 5G-GUTI / 5G-S-TMSI if it got an TMSI allocated following a registration using SUCI.
All 5GC requires at least registration using SUCI, so it's weird it's not working for you.
Could you share your PacketRusher configuration, logs as well a pcap if possible?
Thanks a lot!
Valentin

**Comment by linouxis9** [comment] 2024-06-04 06:36
Hi @hug0lin,
Any updates on your issue?
Thanks a lot!
Valentin

**Comment by linouxis9** [comment] 2024-07-27 14:02
I'm closing this issue as I can't reproduce it, but please feel free to reopen it with the requested informations and you still have some issues.
Thanks!

**Closed by linouxis9** 2024-07-27 14:02 UTC
Labels: bug
